"""dfc3ffcb27fb

Revision ID: e2f0f238bace
Revises: 9b71a87ecca4
Create Date: 2024-06-07 20:09:41.409200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f0f238bace'
down_revision: Union[str, None] = '9b71a87ecca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
